server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 129.204.200.206
aliyun:
  sms:
    accessKeyId: "id"
    accessKeySecret: "秘钥"
    template_code: "模板名称"
    sign_name: "签名"
