server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.200.206:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itecast
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  # 模块跨域访问
  instance:
    prefer-ip-address: true
