server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 129.204.200.206
      database: spitdb
  redis:
    host: 129.204.200.206
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  # 模块跨域访问
  instance:
    prefer-ip-address: true