server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.200.206:3306/tensquare_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 129.204.200.206
  rabbitmq:
    host: 129.204.200.206
jwt:
  config:
    key: itecast
    ttl: 3600000